export type Record = {_id: number,
CHOPER: string,
CHFLTN: string,
CHOPERD: string,
CHSTOL: string,
CHPTOL: string,
CHAORD: string,
CHLOC1: string,
CHLOC1D: string,
CHLOC1TH: string,
CHLOC1T: string,
CHLOC1CH: string,
CHLOCCT: string,
CHTERM: string,
CHCINT: string,
CHCKZN: string,
CHRMINE: string,
CHRMINH: string
}